### ISSUE TITLE
different behavior sometime in server-side rendering at build time  

### ISSUE THREAD

**Issue by navin10sharma** [rangle/angular-ssr#66]
Hello guys 

Thanks for this wonderful module . 

I have one one angular 4 app and i try to render it on build time and uploaded to my aws s3 bucket .

1. First issue once page you can see header part load with just HTML then css load after sometime and then apply on header parts.

2. Another issue i thought once initial home page load rest all the page load in background and app will behave like single page app afterward but not in my case . sometime it work like single page app load pages without refresh but sometime it refresh the complete page to load route. 

You may check this my testing server build.
http://newsionicfirebaseapp.s3-website-us-west-2.amazonaws.com/

Thanks
Navin

**Comment by clbond** [comment]
Hi @navin10sharma. From what I can tell your site is working great. The pages are properly server-side rendered (products, services, etc). preboot is capturing clicks and replaying them correctly.

Your site does have some performance problems but those don't seem to be related to server-side rendering. Your homepage has 8MB worth of images it has to download in order to finish rendering. You should optimize and shrink these images and just generally try to avoid huge network requests (2 separate png images are 3MB each).

Also from your description, I don't understand the actual issue. If there is one please give me easy steps to reproduce it on your site so I can understand what you are talking about.
